const BAD_REQUEST = 400;
const OK = 200;
const CREATED = 201;
const UNAUTHORIZED = 401;
const UNPROCESSABLE_ENTITY = 422;
const INTERNAL_SERVER_ERROR = 500;

export {
  BAD_REQUEST,
  OK,
  CREATED,
  UNAUTHORIZED,
  UNPROCESSABLE_ENTITY,
  INTERNAL_SERVER_ERROR,
};
